version: 2.1
executors:
  test:
    docker:
      - image: hashicorp/terraform:light
jobs:
  test:
    executor:
      name: test
    steps:
      - checkout
      - run:
          name: Inittialize
          command: |
            terraform init
      - run:
          name: Check Plan
          command: |
            terraform plan

workflows:
  test:
    jobs:
      - test
