version: 2.1
executors:
  validater:
    docker:
      - image: wata727/tflint
  deployer:
    docker:
      - image: hashicorp/terraform:light
jobs:
  validate:
    executor:
      name: validater
    steps:
      - checkout
      - run:
          name: Validation check by tflint
          command : tflint
  deploy:
    executor:
      name: deployer
    steps:
      - checkout
      - run:
          name: Inittialize
          command: |
            terraform init
      - run:
          name: Deploy
          command: |
            terraform apply -auto-approve

workflows:
  test:
    jobs:
      - validate
      - deploy:
          requires:
            - validate
          filters:
            branches:
              only: master